# Generated by Django 5.2.14 on 2026-05-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="策略名称")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "content_md",
                    models.TextField(blank=True, verbose_name="详细说明（Markdown）"),
                ),
                ("code_link", models.URLField(blank=True, verbose_name="代码链接")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "策略",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="信号日期")),
                ("summary", models.TextField(blank=True, verbose_name="信号摘要")),
                (
                    "details_json",
                    models.JSONField(blank=True, default=dict, verbose_name="详细数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="strategies.strategy",
                        verbose_name="策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "策略信号",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="回测日期")),
                (
                    "annual_return",
                    models.FloatField(blank=True, null=True, verbose_name="年化收益率"),
                ),
                (
                    "sharpe_ratio",
                    models.FloatField(blank=True, null=True, verbose_name="夏普比率"),
                ),
                (
                    "max_drawdown",
                    models.FloatField(blank=True, null=True, verbose_name="最大回撤"),
                ),
                (
                    "win_rate",
                    models.FloatField(blank=True, null=True, verbose_name="胜率"),
                ),
                (
                    "metrics_json",
                    models.JSONField(blank=True, default=dict, verbose_name="其他指标"),
                ),
                ("chart_html", models.TextField(blank=True, verbose_name="图表 HTML")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="strategies.strategy",
                        verbose_name="策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测结果",
                "ordering": ["-date"],
            },
        ),
    ]
