# Generated by Django 5.2.14 on 2026-05-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="标题"),
                ),
                (
                    "content_md",
                    models.TextField(blank=True, verbose_name="内容（Markdown）"),
                ),
                ("market_note", models.TextField(blank=True, verbose_name="盘面简评")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="已发布"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "每日市场快照",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                ("url", models.URLField(blank=True, verbose_name="原文链接")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("manual", "手动"),
                            ("api", "API"),
                            ("email", "邮件"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="来源渠道",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="来源名称"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="作者"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                ("content_text", models.TextField(blank=True, verbose_name="全文")),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="标签"),
                ),
                (
                    "people",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="相关人物"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="收藏"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布日期"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="market.dailysnapshot",
                        verbose_name="关联快照",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
