# Generated by Django 5.2.14 on 2026-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RssSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("feed_url", models.URLField(unique=True, verbose_name="RSS 地址")),
                ("site_url", models.URLField(blank=True, verbose_name="网站地址")),
                (
                    "category",
                    models.CharField(blank=True, max_length=50, verbose_name="分类"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_fetched",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次抓取"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "RSS 订阅源",
                "ordering": ["name"],
            },
        ),
    ]
