# Generated by Django 5.2.14 on 2026-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_rsssource"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_translated",
            field=models.TextField(blank=True, verbose_name="中文翻译"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_text",
            field=models.TextField(blank=True, verbose_name="原文全文"),
        ),
    ]
