# Generated by Django 5.2.14 on 2026-05-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "笔记分类",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="标签（逗号分隔）"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                ("content_md", models.TextField(verbose_name="内容（Markdown）")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notes.notecategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习笔记",
                "ordering": ["-created_at"],
            },
        ),
    ]
