# Generated by Django 5.2.14 on 2026-05-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_zh", models.CharField(max_length=100, verbose_name="中文名称")),
                ("name_ja", models.CharField(max_length=100, verbose_name="日本語名")),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="English name"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_zh", models.CharField(max_length=200, verbose_name="中文标题")),
                (
                    "title_ja",
                    models.CharField(max_length=200, verbose_name="日本語タイトル"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="English title"),
                ),
                (
                    "description_zh",
                    models.TextField(blank=True, verbose_name="中文描述"),
                ),
                (
                    "description_ja",
                    models.TextField(blank=True, verbose_name="日本語説明"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="English description"),
                ),
                (
                    "location_zh",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="中文地点"
                    ),
                ),
                (
                    "location_ja",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="日本語場所"
                    ),
                ),
                (
                    "location_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="English location"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基准价格"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="时长(分钟)"),
                ),
                (
                    "max_participants",
                    models.IntegerField(default=10, verbose_name="最大参与人数"),
                ),
                (
                    "min_participants",
                    models.IntegerField(default=1, verbose_name="最少成团人数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="上架")),
                ("featured", models.BooleanField(default=False, verbose_name="推荐")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="图片"),
                ),
                (
                    "caption_zh",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="中文说明"
                    ),
                ),
                (
                    "caption_ja",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="日本語説明"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="English caption"
                    ),
                ),
                ("is_cover", models.BooleanField(default=False, verbose_name="封面图")),
                ("order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品图片",
                "verbose_name_plural": "产品图片",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductDatePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="当日价格"
                    ),
                ),
                (
                    "available_qty",
                    models.IntegerField(default=0, verbose_name="可用库存"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="可预订"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_prices",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "日期价格",
                "verbose_name_plural": "日期价格",
                "unique_together": {("product", "date")},
            },
        ),
    ]
